"""Add universe_id to Rulebook

Revision ID: 3b3c94b566e5
Revises: 5671f1da7a8c
Create Date: 2025-06-11 05:13:55.349597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3c94b566e5'
down_revision = '5671f1da7a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
