"""Add universe_id to Rulebook

Revision ID: 3b3c94b566e5
Revises: 5671f1da7a8c
Create Date: 2025-06-11 05:13:55.349597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3c94b566e5'
down_revision = '5671f1da7a8c'
branch_labels = None
depends_on = None


def upgrade():
    # Add universe_id column and foreign key to rulebook table using batch mode for SQLite compatibility
    with op.batch_alter_table('rulebook') as batch_op:
        batch_op.add_column(sa.Column('universe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_rulebook_universe', 'universe', ['universe_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # Remove universe_id column and foreign key from rulebook table using batch mode
    with op.batch_alter_table('rulebook') as batch_op:
        batch_op.drop_constraint('fk_rulebook_universe', type_='foreignkey')
        batch_op.drop_column('universe_id')

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
