"""Universe and sharing models

Revision ID: 5671f1da7a8c
Revises: 8fb03904f77a
Create Date: 2025-06-11 05:10:26.083735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5671f1da7a8c'
down_revision = '8fb03904f77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
