"""Universe and sharing models

Revision ID: 8fb03904f77a
Revises: e3afc81456d4
Create Date: 2025-06-11 05:10:19.813545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8fb03904f77a'
down_revision = 'e3afc81456d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universe',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('owner_id', sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_universe_share',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('universe_id', sa.Integer(), sa.ForeignKey('universe.id'), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_universe_share')
    op.drop_table('universe')
    # ### end Alembic commands ###
